## Initialization Libraries.

In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import math
from scipy import stats

In [5]:
df = pd.read_csv("health_dataset.csv")
df

,record_id,age_group,age,weight,gender,region,smoking_status,exercise_frequency,bmi,blood_pressure,diabetes,hypertension,cholesterol_level,glucose_level,visit_date
0,1001,60+,63,100,Other,West,Former Smoker,Rarely,23.73,133.1,False,False,246.8,117.1,25-09-2025
1,1002,60+,66,52,Female,West,Smoker,Never,20.76,158.2,True,True,177.3,85.6,21-09-2025
2,1003,46-60,53,57,Other,East,Former Smoker,Weekly,18.98,147.3,True,False,190.5,139.0,29-12-2025
3,1004,46-60,54,56,Other,East,Non-Smoker,Rarely,18.64,138.6,True,False,159.7,106.3,10-02-2026
4,1005,18-25,21,93,Other,West,Former Smoker,Weekly,25.10,134.7,True,True,229.0,106.9,07-07-2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,1176,18-25,19,64,Female,South,Non-Smoker,Never,31.09,138.2,False,False,242.2,163.1,08-07-2025
176,1177,36-45,44,74,Male,East,Non-Smoker,Weekly,34.68,144.0,False,True,236.8,156.7,19-03-2026
177,1178,18-25,23,75,Male,South,Smoker,Never,28.14,130.9,True,False,246.4,164.8,22-10-2025
178,1179,46-60,57,94,Other,South,Former Smoker,Daily,27.71,109.7,True,True,274.7,126.1,19-06-2025
179,1180,60+,72,103,Other,West,Non-Smoker,Never,24.34,125.9,True,True,277.6,122.0,18-04-2025

In [6]:
df.head()

,record_id,age_group,age,weight,gender,region,smoking_status,exercise_frequency,bmi,blood_pressure,diabetes,hypertension,cholesterol_level,glucose_level,visit_date
0,1001,60+,63,100,Other,West,Former Smoker,Rarely,23.73,133.1,False,False,246.8,117.1,25-09-2025
1,1002,60+,66,52,Female,West,Smoker,Never,20.76,158.2,True,True,177.3,85.6,21-09-2025
2,1003,46-60,53,57,Other,East,Former Smoker,Weekly,18.98,147.3,True,False,190.5,139.0,29-12-2025
3,1004,46-60,54,56,Other,East,Non-Smoker,Rarely,18.64,138.6,True,False,159.7,106.3,10-02-2026
4,1005,18-25,21,93,Other,West,Former Smoker,Weekly,25.10,134.7,True,True,229.0,106.9,07-07-2025

In [7]:
df.tail()

,record_id,age_group,age,weight,gender,region,smoking_status,exercise_frequency,bmi,blood_pressure,diabetes,hypertension,cholesterol_level,glucose_level,visit_date
175,1176,18-25,19,64,Female,South,Non-Smoker,Never,31.09,138.2,False,False,242.2,163.1,08-07-2025
176,1177,36-45,44,74,Male,East,Non-Smoker,Weekly,34.68,144.0,False,True,236.8,156.7,19-03-2026
177,1178,18-25,23,75,Male,South,Smoker,Never,28.14,130.9,True,False,246.4,164.8,22-10-2025
178,1179,46-60,57,94,Other,South,Former Smoker,Daily,27.71,109.7,True,True,274.7,126.1,19-06-2025
179,1180,60+,72,103,Other,West,Non-Smoker,Never,24.34,125.9,True,True,277.6,122.0,18-04-2025

In [11]:
print(df.dtypes)

record_id               int64
age_group              object
age                     int64
weight                  int64
gender                 object
region                 object
smoking_status         object
exercise_frequency     object
bmi                   float64
blood_pressure        float64
diabetes                 bool
hypertension             bool
cholesterol_level     float64
glucose_level         float64
visit_date             object
dtype: object

In [10]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   record_id           180 non-null    int64
 1   age_group           180 non-null    object
 2   age                 180 non-null    int64
 3   weight              180 non-null    int64
 4   gender              180 non-null    object
 5   region              180 non-null    object
 6   smoking_status      180 non-null    object
 7   exercise_frequency  180 non-null    object
 8   bmi                 180 non-null    float64
 9   blood_pressure      180 non-null    float64
 10  diabetes            180 non-null    bool
 11  hypertension        180 non-null    bool
 12  cholesterol_level   180 non-null    float64
 13  glucose_level       180 non-null    float64
 14  visit_date          180 non-null    object
dtypes: bool(2), float64(4), int64(3), object(6)
memory usage: 18.8+ KB
None

### Formulate Hypotheses (Print)

In [12]:
print("H0: Smoking has no effect on Diabetes.")
print("H1: Smoking affects Diabetes.")

print("\nH0: Mean BMI of Male and Female is equal.")
print("H1: Mean BMI of Male and Female is different.")

H0: Smoking has no effect on Diabetes.
H1: Smoking affects Diabetes.

H0: Mean BMI of Male and Female is equal.
H1: Mean BMI of Male and Female is different.

### Confidence Interval (Example: Age & Weight)

In [15]:
# Age CI
mean_age = df['age'].mean()
std_age = df['age'].std()
n = len(df)

ci_age = stats.t.interval(0.95, df=n-1, loc=mean_age, scale=std_age/np.sqrt(n))

print("95% CI for Age:", ci_age)

# Weight CI
mean_weight = df['weight'].mean()
std_weight = df['weight'].std()

ci_weight = stats.t.interval(0.95, df=n-1, loc=mean_weight, scale=std_weight/np.sqrt(n))

print("95% CI for Weight:", ci_weight)

95% CI for Age: (np.float64(45.303311113616466), np.float64(49.985577775272425))
95% CI for Weight: (np.float64(73.91435424643232), np.float64(79.51897908690101))

### Z-Test (Approx using large sample)

In [16]:
# Z-test for BMI mean (assume population mean = 25)
sample_mean = df['bmi'].mean()
sample_std = df['bmi'].std()
n = len(df)

z = (sample_mean - 25) / (sample_std / np.sqrt(n))
p_value = 2 * (1 - stats.norm.cdf(abs(z)))

print("Z-value:", z)
print("P-value:", p_value)

Z-value: 3.4492465571209947
P-value: 0.0005621531600004115

### T-Test (Male vs Female BMI)

In [17]:
male_bmi = df[df['gender'] == 'Male']['bmi']
female_bmi = df[df['gender'] == 'Female']['bmi']

t_stat, p_val = stats.ttest_ind(male_bmi, female_bmi)

print("T-statistic:", t_stat)
print("P-value:", p_val)

T-statistic: 1.0829229290732505
P-value: 0.2811278326101961

### Chi-Square Test (Smoking vs Diabetes)

In [18]:
cont_table = pd.crosstab(df['smoking_status'], df['diabetes'])

chi2, p, dof, expected = stats.chi2_contingency(cont_table)

print("Chi-square value:", chi2)
print("P-value:", p)

Chi-square value: 0.6775485789594781
P-value: 0.7126432820236124

### ANOVA Test (BMI across Age Groups)

In [19]:
groups = [group['bmi'].values for name, group in df.groupby('age_group')]

f_stat, p_val = stats.f_oneway(*groups)

print("F-statistic:", f_stat)
print("P-value:", p_val)

F-statistic: 1.5413571724324837
P-value: 0.19225672406859914

### Covariance & Correlation (Age vs BMI)

In [20]:
covariance = np.cov(df['age'], df['bmi'])[0][1]
correlation = np.corrcoef(df['age'], df['bmi'])[0][1]

print("Covariance:", covariance)
print("Correlation:", correlation)

Covariance: -13.082319056486652
Correlation: -0.15972807804340775

### Final Interpretation (Auto Decision)

In [21]:
alpha = 0.05

def decision(p):
    return "Reject H0" if p < alpha else "Fail to Reject H0"

print("Z-test decision:", decision(p_value))
print("T-test decision:", decision(p_val))
print("Chi-square decision:", decision(p))
print("ANOVA decision:", decision(p_val))

Z-test decision: Reject H0
T-test decision: Fail to Reject H0
Chi-square decision: Fail to Reject H0
ANOVA decision: Fail to Reject H0